spring:
  application:
      name: Library

  datasource:
    url: jdbc:mysql://localhost:3306/library_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345



  jpa.show-sql: true
  jpa.hibernate.ddl-auto: update
